### ISSUE TITLE
[1.0.0.8] Readiness probes are read from liveness probes in gateway runtime

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/kubernetes-microgateway#101]
**Description:**

Existing template.
```yaml
          readinessProbe:
            exec:
              command: [ "sh", "check_health.sh" ]
            initialDelaySeconds: {{ .Values.wso2.deployment.gatewayRuntime.enforcer.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wso2.deployment.gatewayRuntime.enforcer.livenessProbe.periodSeconds }}
```

Should be as follows.
```yaml
          readinessProbe:
            exec:
              command: [ "sh", "check_health.sh" ]
            initialDelaySeconds: {{ .Values.wso2.deployment.gatewayRuntime.enforcer.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wso2.deployment.gatewayRuntime.enforcer.readinessProbe.periodSeconds }}
```
