### ISSUE TITLE
[1.1.0.7] Readiness probes are read from liveness probes in gateway runtime

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/kubernetes-microgateway#103]
**Description:**

Existing template.
```yaml
          readinessProbe:
            exec:
              command: [ "sh", "check_health.sh" ]
            initialDelaySeconds: {{ .Values.wso2.deployment.gatewayRuntime.enforcer.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wso2.deployment.gatewayRuntime.enforcer.livenessProbe.periodSeconds }}
```

Should be as follows.
```yaml
          readinessProbe:
            exec:
              command: [ "sh", "check_health.sh" ]
            initialDelaySeconds: {{ .Values.wso2.deployment.gatewayRuntime.enforcer.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wso2.deployment.gatewayRuntime.enforcer.readinessProbe.periodSeconds }}
```

Related Issue: https://github.com/wso2/kubernetes-microgateway/issues/101
