### ISSUE TITLE
[1.1.0.3] Mount empty dir to write Router heap/CPU profile data

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/kubernetes-microgateway#45]
**Description:**
Router store heap/CPU profile data when profiling enabled and store it in ``. Since the container in the pod has a read-only file system, we can mount an empty dir to write profile data.

Config:
```yaml
debug:
  # Store heap profile data for analyzing memory leaks
  heapProfile:
    # Mount an K8s empty dir to write profile data
    mountEmptyDir: false
    # Path to mount the empty dir
    mountPath: /var/log/envoy
```

Docs: https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/debug-memory/
