### ISSUE TITLE
[1.1.0.3] Override Docker registry in component level

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/kubernetes-microgateway#46]
**Description:**
We can define the Docker registry using `wso2.deployment.dockerRegistry` and this will apply to all components (adapter, enforcer, router).

Introduce component level config to Docker registry is required.

For example for router:

```yaml
router:
    # Docker registry. If this value is not empty, this overrides the value in 'wso2.deployment.dockerRegistry'
    dockerRegistry: ""
    # Image name for router
    imageName: "choreo-connect-router"
    # Image tag for router
    imageTag: "1.1.0"
    # Refer to the Kubernetes documentation on updating images (https://kubernetes.io/docs/concepts/containers/images/#updating-images)
    imagePullPolicy: IfNotPresent
```
