### ISSUE TITLE
[1.1.0.6] Error applying Router backendCaCerts

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/kubernetes-microgateway#74]
**Description:**
Set following in the values.yaml file under `wso2.deployment.gatewayRuntime.router`

```yaml
        security:
          # Trusted backend certs in PEM format
          backendCaCerts:
            secretName: "trusted-ca-certs"
            subPath: "ca-certs.crt"
```

Install helm chart
```
Error: YAML parse error on choreo-connect/templates/gateway-runtime-deployment.yaml: error converting YAML to JSON: yaml: line 176: could not find expected ':'
```
