### ISSUE TITLE
[1.0.0.8] Mount files to truststore with a manual name

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/kubernetes-microgateway#99]
### Description
When truststore is specified with a secret name and subpath the file mounted to the container is auto-generated by helm chart with the name `{secretName}-{subPath | replace "." with "-"}.pem`.
```yaml
        truststore:
            secretName: "control-plane-cert"
            subPath: "tls.crt"
```

For the above sample, it is `control-plane-cert-tls-crt.pem`.
Having a user-defined value is nice to have.

### Related Issue
#97
